### ISSUE TITLE
Model completely without textures

### ISSUE THREAD

**Issue by dev-zetta** [cedricpinson/osgjs#1010]
Hello,
I've been struggeling with osgjs for days... It simply does not display textures. I tried osgjs and gltf format (parser is really flawed).

Lights, no lights. I debugged the code and the textures are loaded, everything looks fine, but they are simply not applied to the meshes. The material looks as single color.

![image](https://user-images.githubusercontent.com/3283719/58698473-9edd8d00-839b-11e9-8597-187c63b827bc.png)

**Comment by jtorresfabra** [comment]
Hi @dev-zetta, osgjs is discontinued, so you might not have any answer in this repository. Anyway is not possible that anybody helps you without posting example code or explaining what you did.

**Comment by dev-zetta** [comment]
Thank you for the answer. I did some bugfixes on the gltf loader. However, the problem was in osgjs itself. There is no default shader for rendering models/meshes that use color/diffuse texture. After I implemented this shader, I finally got it working. However, there were glitches. So we abandoned osgjs and switched to Three.js. Now everything works as expected.
