### ISSUE TITLE
PageLOD should not release data during the update traversal

### ISSUE THREAD

**Issue by cedricpinson** [cedricpinson/osgjs#206]
Camera should not contain the graphic context. The release of gl data should be done in another traversal, like draw / cull. Could you have a look where it's done in osg ?
https://github.com/cedricpinson/osgjs/blob/issue-200/sources/osg/PagedLOD.js#L231
@jtorresfabra ping

**Comment by cedricpinson** [comment]
thank you very much and happy new year :)

**Comment by jtorresfabra** [comment]
It should be fixed by #231
