### ISSUE TITLE
Add osgUtil visitor to release texture not used in the scenegraph

### ISSUE THREAD

**Issue by cedricpinson** [cedricpinson/osgjs#213]
Javascript does not handle destructor, so to release texture allocated but not used in the subgraph we could use a visitor that check the entire scenegraph and release all texture not attached to it. Off course it must be controlled by the user.

**Comment by cedricpinson** [comment]
Using a marker seems the best solution to says we dont want this texture anymore

**Comment by jtorresfabra** [comment]
Is it fixed in #297? If it is, then it can be closed.
