### ISSUE TITLE
Matrix.makeRotate is wrong

### ISSUE THREAD

**Issue by stephomi** [cedricpinson/osgjs#218]
Just for information Matrix.makeRotate rotates in the wrong direction (Quat.makeRotate is correct).
(@jtorresfabra)

    osg.Matrix.makeRotateFromQuat(osg.Quat.makeRotate(Math.PI/2,1,0,0,[]),[])
    >[1, 0, 0, 0, 0, 0, 1, 0, 0, -1, 0, 0, 0, 0, 0, 1]
    osg.Matrix.makeRotate(Math.PI/2,1,0,0,[])
    >[1, 0, 0, 0, 0, 0, -1, 0, 0, 1, 0, 0, 0, 0, 0, 1]

**Comment by jtorresfabra** [comment]
@stephomi I am not the author of these methods. Or at least I don't recall implementing or modifiying any of them. I've just looked at the history and it seems that methods are there from at least Dec 2013. 

If it was just for info thanks, good to know.

**Comment by stephomi** [comment]
Yep I know it's not you (it's a very old function) it was just for info. : )

Since it's the kind of function that is used a lot, if we fix it it might break a thing or two obviously.

**Comment by stephomi** [comment]
PR at https://github.com/cedricpinson/osgjs/pull/285
