### ISSUE TITLE
Materials not applied to Lines

### ISSUE THREAD

**Issue by jtorresfabra** [cedricpinson/osgjs#232]
It seems that materials are not applied to Line primitiveSets. Some time ago it used to work ok. So it's something 'new'.

**Comment by cedricpinson** [comment]
do you have an example ?

**Comment by jtorresfabra** [comment]
Ummm, I need to check some stuff first. I am closing this issue, I will reopen it when I have a code example.

**Comment by jtorresfabra** [comment]
Forget it, it works as intended, my bad.
