### ISSUE TITLE
[GC perf] Replace new Cullsettings by Cullsettings stack in CullVisitor

### ISSUE THREAD

**Issue by Kuranes** [cedricpinson/osgjs#239]
New is there:
https://github.com/cedricpinson/osgjs/blob/develop/sources/osg/CullVisitor.js#L452
(The stack could be stored, either with all other in cullstack https://github.com/cedricpinson/osgjs/blob/develop/sources/osg/CullStack.js#L18 )

**Comment by Kuranes** [comment]
The new is still there ?https://github.com/cedricpinson/osgjs/blob/c734aaa67cf070fa4658fb9c2b4787094ecbfdb6/sources/osg/CullVisitor.js#L260

**Comment by cedricpinson** [comment]
Ho sorry

**Comment by cedricpinson** [comment]
it's done right ?

**Comment by Kuranes** [comment]
It is done. we can close

**Comment by Kuranes** [comment]
Fixed by https://github.com/cedricpinson/osgjs/commit/c6b90051c0c9046793a0d01287e11e5c567e0f2a
