### ISSUE TITLE
[Perf] Matrix isIdentity Bench usage for Complex Matrix computations

### ISSUE THREAD

**Issue by Kuranes** [cedricpinson/osgjs#242]
Many osg matrix computation ends with a matrix identity, using a compare to Matrix.identity before doing any complex computation (transformVec,Bbox,Sphere and matrix Mutl/inverse.) could give some nice perfs.
It also ease a lot debugging session when matrix are involved. (projection/view/world related computations)

**Comment by cedricpinson** [comment]
need to be tested/simulated I think we would get more perf caching stuff per frame aka culling
