### ISSUE TITLE
Code Crahes on Texture Module

### ISSUE THREAD

**Issue by hishamabdelrahman** [cedricpinson/osgjs#273]
hi all,
I got intermittent issue where code crashes on Texture Module at 
function :applyTexImage2D
At line  gl.texImage2D.apply( gl, args ); I got undefined error
I am using PagedLOD Model
Data that is replicating this error is residing on the following link
https://drive.google.com/file/d/0B9Z19aal418PM04xbUhuRG5ONHc/view?usp=sharing
best regards

**Comment by jtorresfabra** [comment]
Hi, 

Did you try with the Chrome dev tools console? Sometimes it give more clues of what is happening. 

What I experienced with your database was a run out of texture memory (some times), it could be related. I will give a try again to your data as soon as I can. In the meantime try the chrome dev tools to see if you can narrow down the issue, or to have more clues about it. 

Thanks

**Comment by hishamabdelrahman** [comment]
i had tried to replicate the issue on Chrome several times , however its not replicated , it may be a problem related to IE

**Comment by jtorresfabra** [comment]
Can you see if you can replicate it with the latest changes? I mean with IE

**Comment by hishamabdelrahman** [comment]
still on IE I can replicate the error

**Comment by jtorresfabra** [comment]
Also in http://webkeux.com/deletingTextures? What I get is: 
WEBGL11003: INVALID_VALUE: pixelStorei
But no undefined error.
I'm using Win7 and IE11

**Comment by hishamabdelrahman** [comment]
That error is always replicated on IE   WEBGL11003: INVALID_VALUE:
pixelStorei but it doesn't crash the viewer , however the undefined error
is intermittent error where it crashes the viewer .
I am also using same win7 and IE 11
BTW , I am loading huge dataset of total 43.3 GB of coarse pagedLOD is
taking care of which levels and tiles would be loaded.

I was thinking that the error  had something to do with the error fixed
[osgjs] Bugfix/ie glsl preprocessor shortcoming (#292) , but apparently its
not.

**Comment by cedricpinson** [comment]
Are you sure it s not simply your app consume too much memory ?

**Comment by hishamabdelrahman** [comment]
hi All,
I had been testing so many scenarios and cases , one of them i got the out of memory error and then crashes , when I enabled the option in IE enable 64 bit processes for enhanced protected mode as well as enable Enhanced protected mode , I can now cannot see that error as frequent as before , it can be too much related to consumption of memory as my data is too much.
I will continue testing , if i find any other root cause for that i will report it
many thanks

**Comment by jtorresfabra** [comment]
For the memory consumption you can try to have a more severe policy with PLOD nodes. 
The DatabasePager class has a set/get TargetMaximumNumberOfPageLOD method. That number represent the number of nodes in cache (in memory) and the default value is 75. 

You can try to reduce that value i.e.: viewer.getDatabasePager().setTargetMaximumNumberOfPageLOD(25)

**Comment by hishamabdelrahman** [comment]
Thanks Jordi , i will try that option as well 
best regards

**Comment by hishamabdelrahman** [comment]
this issue is so old .. .lots of enhancements had been done so far , i cant see that issue for long . so i am closing this for  now
