### ISSUE TITLE
PagedLOD is not freeing memory anymore

### ISSUE THREAD

**Issue by hishamabdelrahman** [cedricpinson/osgjs#291]
i believe that the issue is coming from the following

In Node Class
the function releaseGLObjects doesnot pass state object as well as when calling the stateset.releaseGLObjects we dont pass the expected state object

  releaseGLObjects: function ( /*gl*/) {

           
            if ( this.stateset !== undefined ) this.stateset.releaseGLObjects();
        }

then in stateset Class the Function releaseGLObjects  which Expects state object 

  releaseGLObjects: function ( state ) {
            // TODO: We should release Program/Shader attributes too
            for ( var i = 0, j = this.textureAttributeMapList.length; i < j; i++ ) {
                this.getTextureAttribute( i, 'Texture' ).releaseGLObjects( state );
            }
        },
as state is passed as null this  will result to  fail to release the texture when the releaseGLObjects is called on the texture Class as state would always be passed as undefined

 releaseGLObjects: function ( state ) {
            if ( state !== undefined ) {
                if ( this._textureObject !== undefined && this._textureObject !== null ) {
                    state.getTextureManager().releaseTextureObject( this._textureObject );
                    this._textureObject = undefined;
                }
            }
        },

The Intial Code was working for object.releaseGLObjects as the texture as it was not expecting a state object

releaseGLObjects: function ( ) {
            if ( this._textureObject !== undefined && this._textureObject !== null ) {
                Texture.textureManager.releaseTextureObject( this._textureObject );
                this._textureObject = undefined;
                this._image = undefined;
            }
        },

**Comment by jtorresfabra** [comment]
Hi @hishamabdelrahman 
There is more work to be done, but can you try https://github.com/cedricpinson/osgjs/pull/297 to see if it fixes the issues for you? thanks.

**Comment by hishamabdelrahman** [comment]
Thanks jordi ..I saw your pull request .u believe it should fix my issue
...many thanks for Ur support

**Comment by jtorresfabra** [comment]
it can be closed, fixed in #297

**Comment by hishamabdelrahman** [comment]
i verified the latest code with my data , yes its working well now
