### ISSUE TITLE
Handle .gz file when server incorrectly set headers ( like gh-pages...)

### ISSUE THREAD

**Issue by Kuranes** [cedricpinson/osgjs#300]
Add a zlib javascript zlib:
native &  small from 
https://github.com/imaya/zlib.js/tree/master/bin
or
ported using ecmscipten to asm.js
https://github.com/ukyo/zlib-asm

Then detect the case of wrong server header.
(need try catch around the data reader from xhr and try decomp there)

(we cannot update osgjs.org website until this is done, otherwise all sample suing the basic model doesn't work)

**Comment by Kuranes** [comment]
adding https://github.com/thehyve/dalliance-plugin/tree/master/web-app/jszlib
found in this (old) bench 
http://jsperf.com/three-zlibs/3

**Comment by cedricpinson** [comment]
fixed
