### ISSUE TITLE
ShadowCasting culling might alter main camera projection

### ISSUE THREAD

**Issue by Kuranes** [cedricpinson/osgjs#305]
Using osgjs, but cannot reproduce in a osgjs minimal sample, using shadow casting spotlight and light editing feature via osgUtil::gizmo gave a single frame bad projection matrix.
-> might be related, missing bits in osgjs that are in osg:
OSG: https://github.com/openscenegraph/osg/blob/dc5cffcdd0da30abdae16cc76bac0ef225004b9c/src/osgUtil/CullVisitor.cpp#L1636
OSGJS https://github.com/cedricpinson/osgjs/blob/e8ee0aafd653830ae70d8818c667f8241c95d9af/sources/osg/CullVisitor.js#L319

.

**Comment by cedricpinson** [comment]
out of date I guess
