### ISSUE TITLE
Unnecessary GL states call at "end of Renderer:draw" frame(up and above 18 gl state calls)

### ISSUE THREAD

**Issue by Kuranes** [cedricpinson/osgjs#399]
repro steps:
run a sample, capture a glTrace with gl inspector, see all call after the last gl.DrawElement to end of frame.

Comment  State.apply here:
https://github.com/cedricpinson/osgjs/blob/a4587df5d542736eb45da16244db8f3d0c543c20/sources/osgViewer/Renderer.js#L193

re-run same sample, capture a  gltrace with glinspector.

And see that all the unnecessary calls are removed.

All samples/tutorial runs well without but "multiple viewer" sample

But it shouldn't be enabled in all the other use case, as GL call are very costly  (and pollute gl traces)

In case of FOG sample, half the gl call are unnecessary (18/36).

if use case is to "revert webgl state to a neutral state", better just share the "lastapplied" states thing between frame/viewers as it would allows for even fewer states on usecase where states are always the same during and between frames/viewers.)

**Comment by stephomi** [comment]
When we create a viewer, when the run() function is called, it creates a shader without material, triggered by

https://github.com/cedricpinson/osgjs/blob/develop/sources/osgViewer/Renderer.js#L193

The shader is not send to the cg and is not used, so it's not really a problem but maybe we can prevent the useless code execution

**Comment by cedricpinson** [comment]
Since a lot of stuff has been fixed to avoid duplicate state, it should be fixed
