### ISSUE TITLE
ShadowCast Compiler Generated Shader are not Cached/Shared between lights.

### ISSUE THREAD

**Issue by Kuranes** [cedricpinson/osgjs#401]
shaderGenerator::getOrCreateProgram create a cache key from attribute hash which include many inherited StatesAttributes (and texture attributes).

But in case of shadow casting (or any Depth Render) most are not used in effect, making cache key not pertinent.

 It prevents sharing a shadow caster shader program between lights/objects 
=> meaning useless multiple shader program  states change, with its associated uniform states changes
(big perf impact)

Either add specialized code in the generic shader generator, or a specialized (inheritable) shadergenerator for shadow caster attribute.

**Comment by Kuranes** [comment]
Another solution not touching all those would be using a shaderprocessor cache.
Would "intercept" any case falling out of the "hash" cache, but still the same exact shader program.

**Comment by cedricpinson** [comment]
What are the performance impact ? I am not sure it is significant for our usecase, do you have number else we can spend energy on something else.

**Comment by Kuranes** [comment]
It's just a note upon gl trace reading " animation + shadow computed each frame that can easily gives huge number of GL call state. 

Here's the math for numbers:

nb shader state change = nb submesh * nb lights 
instead of = nbsubmesh

In case of animated mesh it's shader state change cost + whole bone uniform upload cost.

Difficult to get number, unless digging/benchmarking by doing with/without the change...

What we know that it impact:

- impact shader compilation time (stuttering at loading: if animated &3 lights that gives 
Nb of shaders =  nb submesh * nb lights. That can be a lot of useless compilation
- fps impact. ( to determine need benchmark)
- "gl call trace" clearing 


Other shadow related performance fix:

-> Useless texture binding is also a big "gl call trace" problem in shadow casting.
Maybe have to benchmark null texture binding, or even try a new kind of attribute state "Disabled Override" that would prevent any binding at all of texture.

-> compute scenebounds once per shadowed scene instead of thrice when using same flags for node mask

**Comment by Kuranes** [comment]
As @stephomi pointed, A specific shadow caster Compiler would ease adding those features, and would give even simpler code, thus more evolutive

**Comment by Kuranes** [comment]
Fixed by ttps://github.com/cedricpinson/osgjs/pull/434
