### ISSUE TITLE
Push/Pop StateSet inconsistent results

### ISSUE THREAD

**Issue by Kuranes** [cedricpinson/osgjs#435]
In the particular case of Shadow, we push and pop statesets

https://github.com/cedricpinson/osgjs/blob/develop/sources/osgShadow/ShadowedScene.js#L91

ReceivingStateSet: 
https://github.com/cedricpinson/osgjs/blob/develop/sources/osgShadow/ShadowedScene.js#L127
CasterStateSet: 
https://github.com/cedricpinson/osgjs/blob/develop/sources/osgShadow/ShadowMap.js#L1017-L1046

And yet, In ShaderGenerator when we get the Attributes and TextureAttributes fro the State for the ShadowCast casterStateSet we get textures and attributes from the Receiver stateset.

**Comment by cedricpinson** [comment]
is there a way to reproduce it with a small example ?

**Comment by Kuranes** [comment]
out of the box shadow example show the bug.

**Comment by cedricpinson** [comment]
could you provide a step by step instructions ?

**Comment by Kuranes** [comment]
open  osgjs/examples/shadowmap/ in chrome
once loaded, check dev tool console log
Expand  "New Compilation=>Object"
Expand  "New Compilation=>Object=>Attributes"

And see that "ShadowReceiveAttribute" is listed 
( in my understanding it should not )

Recall that faked shadowedScene Node does manually fake a hierarchy like
```
                                ShadowedScene 
                                             |
                                             |
           ----------------------------------------------------------------------
          |                                                                                    |
    Receive Scene                                                       Cast Scene
    (with shadow receive attribute)                               ( with shadow cast attribute )
```

**Comment by Kuranes** [comment]
Doh!

Rubber ducking it makes me realize that I should rename the shadowedScene stateset to receiving stateset here as a receiverStateset and don't touch actual shadowedScene Stateset...
https://github.com/cedricpinson/osgjs/blob/develop/sources/osgShadow/ShadowedScene.js#L127

TODO: make two separate stateset...

**Comment by Kuranes** [comment]
Following message above made the separate stateset but still have receive attribute on the shadow caster state. 
https://github.com/cedricpinson/osgjs/pull/444
TODO: have to check that shadowed scene stateset is really a virgin stateset before reup this issue

**Comment by Kuranes** [comment]
So it doesn't fix anything, just makes code clearer:

I guess it comes to why cullvisitor::popStateset does nothing https://github.com/cedricpinson/osgjs/blob/bugfix/shadow-stateset-inheritance/sources/osg/CullVisitor.js#L178 after the shadow receive pass, making shadow cast pass inhering that receive stateset

**Comment by Kuranes** [comment]
Finaly it *was* really fixed by https://github.com/cedricpinson/osgjs/pull/444
