### ISSUE TITLE
osg.objectInehrit typo

### ISSUE THREAD

**Issue by dzeitlin** [cedricpinson/osgjs#462]
should be `osg.objectInherit`

**Comment by stephomi** [comment]
It has been fixed since https://github.com/cedricpinson/osgjs/commit/c734aaa67cf070fa4658fb9c2b4787094ecbfdb6.

Were you checking the develop branch?
The master branch is not up-to-date.

**Comment by dzeitlin** [comment]
Probably, I just downloaded the OSG.zip from https://codeload.github.com/cedricpinson/osgjs/legacy.zip/master
which is I assume was master. Thanks :-)
