### ISSUE TITLE
Cannot view model with Uint32Array

### ISSUE THREAD

**Issue by dkopitsa** [cedricpinson/osgjs#525]
I have a problem with several files. Here a sample (https://dl.dropboxusercontent.com/u/1474489/marg_lite_reduced.obj)
I convert obj file to osgjs with your version of osgconv. 
```
$ osgconv -O "useExternalBinaryArray mergeAllBinaryFiles" marg_lite_reduced.obj preview.osgjs
output:
...skip...
TypedArray Uint32Array preview.bin 351.352 kb
...
```

Then I tried to load model into osgjs viewer. But I have error in console (vb not defined) near https://github.com/cedricpinson/osgjs/blob/develop/sources/osgDB/Input.js#L510 
Can you add support for Uint32Array to osgjs? or maybe there is another way viewing that model in osgjs?

**Comment by cedricpinson** [comment]
Yep if you have a patch dont hesitate to send a pull request, else you can use the pseudo loader gles to convert your model.
```
osgconv -O "useExternalBinaryArray mergeAllBinaryFiles" marg_lite_reduced.obj.gles preview.osgjs
```
it will split your model to fit gles 2.0 requirement.
