### ISSUE TITLE
osgconv can't create jpg file from *.osgb file

### ISSUE THREAD

**Issue by liyihongcug** [cedricpinson/osgjs#614]
osgconv -O "inlineImages" C:\OBJ2GLTF\testobj\osgb\Tile_+000_+001.osgb  C:\OBJ2GLTF\testobj\osgb\Tile_+000_+001.obj
osgconv -O "useExternalBinaryArray mergeAllBinaryFiles" C:\OBJ2GLTF\testobj\osgb\Tile_+000_+001.osgb  C:\OBJ2GLTF\testobj\osgb\Tile_+000_+001.obj
Data written to 'C:\OBJ2GLTF\testobj\osgb\Tile_+000_+001.obj'.

I can see 2 files which genarated ,(*.mtl,*.obj). And mtl file content is below
newmtl material_2
       Ka 0.501961 0.501961 0.501961 1
       Kd 0.501961 0.501961 0.501961 1
       Ks 0 0 0 1

newmtl material_1
       Ka 1 1 1 1
       Kd 1 1 1 1
       Ks 0 0 0 1
       map_Kd Tile_+000_+001_0.jpg===================I can't find this jpg .

why can't jpg file be generated?

**Comment by jtorresfabra** [comment]
@liyihongcug the options you passed to osgconv are exclusive to the osgjs plugin, I mean to convert from osg formats to osgjs ( see https://github.com/cedricpinson/osgjs/wiki/Convert-model-with-OSG ). 
If what you want is to convert from osgb to obj the you should do osgconv -O OutputTextureFiles file.osgb file.obj

You can see all the options on the osgb format doing osgconv --format:

`/osgconv --format osgb
Plugin osgPlugins-3.5.0/osgdb_osg.so
{
    ReaderWriter : OSG Reader/Writer
    {
        features   : readObject readNode writeObject writeNode 
        extensions : .osg                           OpenSceneGraph Ascii file format
        extensions : .osgs                          Pseudo OpenSceneGraph file loaded, with file encoded in filename string
        options    : OutputTextureFiles             Write out the texture images to file
        options    : includeExternalReferences      Export option
        options    : precision                      Set the floating point precision when writing out files
        options    : writeExternalReferenceFiles    Export option
    }
    ReaderWriter : OpenSceneGraph Native Format Reader/Writer
    {
        features   : readObject readImage readNode writeObject writeImage writeNode 
        extensions : .osg2                    OpenSceneGraph extendable format
        extensions : .osgb                    OpenSceneGraph extendable binary format
        extensions : .osgt                    OpenSceneGraph extendable ascii format
        extensions : .osgx                    OpenSceneGraph extendable XML format
        options    : Ascii                    Import/Export option: Force reading/writing ascii file
        options    : Compressor=<name>        Export option: Use an inbuilt or user-defined compressor
        options    : ForceReadingImage        Import option: Load an empty image instead if required file missed
        options    : SchemaData               Export option: Record inbuilt schema data into a binary file
        options    : SchemaFile=<file>        Import/Export option: Use/Record an ascii schema file
        options    : WriteImageHint=<hint>    Export option: Hint of writing image to stream: <IncludeData> writes Image::data() directly; <IncludeFile> writes the image file itself to stream; <UseExternal> writes only the filename; <WriteOut> writes Image::data() to disk as external file.
        options    : XML                      Import/Export option: Force reading/writing XML file
    }
}
`

Also for questions related to the OSG is probably better to do them in the osg-users list/forum.

Cheers.

**Comment by liyihongcug** [comment]
My final destination is to get gltf file. 
1. In This step, I need transform osgb --> (obj mtl jpg) .
   Tips: osgb is oblique photograph file by unmanned aerial vehicle;
2. If success in the last step, I will use OBJ2GLTF plugin to transform obj--> gltf file. OBJ2GLTF plugin need obj that includes jpg file as texture.

But I fail in osg3.4.
 osgconv -O WriteImageHint=IncludeData -O OutputTextureFiles   file.osgb file.obj.
you can try it if u don't believe it.  file.Jpg can't be generated.
I have stopped it for one week.

**Comment by jtorresfabra** [comment]
Hi @liyihongcug 

> 1. In This step, I need transform osgb --> (obj mtl jpg) .
> 2. If success in the last step, I will use OBJ2GLTF plugin to transform obj--> gltf file. OBJ2GLTF plugin need obj that includes jpg file as texture.

These are questions for the OSG user-list not the osgjs project. They are different projects. Here is the place to ask to convert from osgb -> osgjs.

> you can try it if u don't believe it. file.Jpg can't be generated.

If you post an example file I could try.

**Comment by liyihongcug** [comment]
I have sent it to your email(osgis@noreply...). It doesn't support upload.(*.osgb).

Only need transform osgb --> (obj mtl jpg) .

**Comment by jtorresfabra** [comment]
Closing this, as it is not related to osgjs.
