### ISSUE TITLE
How to mark geometry vertex attributes as dirty?

### ISSUE THREAD

**Issue by foo123** [cedricpinson/osgjs#623]
Hello, i'm adding some 3D modifiers support to osg.js with [MOD3](https://github.com/foo123/MOD3)

i have the basic setup ready and examples do work, however geometry is NOT updated after the first modification. i think this happens because after vertices have been modified, the modifier calls the `geometry.dirty()` method. But does nothing. Added `osg.Geometry.enableVAO = true` at the examples still same thing.

Thanks

**Comment by cedricpinson** [comment]
try with osg.Geometry.enableVAO=false, else do you have a minimum sample I could use for debug ?

**Comment by stephomi** [comment]
If you change the vertex attributes data, it's the ``dirty`` method of BufferArray that needs to be called, not the geometry one.

I'm doing it for the gizmo and it works fine : https://github.com/cedricpinson/osgjs/blob/master/sources/osgUtil/NodeGizmo.js#L827-L832

**Comment by jtorresfabra** [comment]
Umm shouldn't the Geometry.dirty() do the trick aswell? https://github.com/cedricpinson/osgjs/blob/master/sources/osg/Geometry.js#L138

It seems it releases the VAO data, so in theory it should be reuploading the data to the video card, ins't it?

**Comment by foo123** [comment]
@cedricpinson, yes the MOD3 repository contains at this point 3 examples with OSG.js in the examples/ folder, you can download and run them, and check the code as well. i used a variation of grid geometry to provide a cube or plane with adequate subdivision so the modifiers like Bend etc have smooth results. They are supposed to be animated, but only the first modification takes place

@stephomi , i'll try that, although i think the `geometry.dirty()` method should do it, if i understand correctly

**Comment by foo123** [comment]
@cedricpinson Plus i have a question whether the modifiers can be used as a kind of transformation node (with the actual geometry node as child), like the `MatrixTransform` nodes but looking at the code for both, could not find a way to apply it. So right now the modifiers are external and can be called to apply anywhere the programmer sees it fit

**Comment by foo123** [comment]
@stephomi yes calling the `buffer.dirty()` method does work, i tested it right now. If this is the best way to do it, i'll update the lib.

Plus it would be nice if the modifiers could be used as a kind of transformation node, in the spirit of scene graph. Else i will leave them as is for now

**Comment by foo123** [comment]
@jtorresfabra yes but it seems the geometry needs an external VAO to actually do any update else it bypasses, https://github.com/cedricpinson/osgjs/blob/master/sources/osg/Geometry.js#L125

**Comment by jtorresfabra** [comment]
@foo123 I don't think extVAO is an external VAO. I think it is the VAO extension, so it checks if the vao extension is present ( and enabled ). Also if it does not do that, the dirty method in Geometry looses the point. Isn't it?

**Comment by foo123** [comment]
@jtorresfabra Most probably you are right, i'm trying to understand the code myself,  `geometry.dirty()` does NOT update the vertex data, whereas the `buffer.dirty()` does (and `geometry.dirtyBound()` also has to be called. (tested them right now and they work perfect, i'm wondering if this is the best way to do it though)

**Comment by foo123** [comment]
Updated the [MOD3](https://github.com/foo123/MOD3) lib using the method by @stephomi for `buffer.dirty()`. It is the final `0.6.0` version. You can download and play with it, it includes several example modifiers for OSG.js (they are just for demonstration, probably better examples could be used). If there are any suggestions for making the lib better for OSG.js, please feel free to contact me (especialy for a way to make modifierStack sth similar to a transformation node ).

Thank you and closing this!
