### ISSUE TITLE
shader-generator and temporal examples are broken

### ISSUE THREAD

**Issue by schmok** [cedricpinson/osgjs#649]
@cedricpinson
I'm playing with osgjs for quite a bit now. 
Seems like the examples mentioned in the subject are broken.

In the console it says 
`Uncaught TypeError: Cannot read property 'slice' of undefined`

Looks like there is no
`osgShader.Compiler.validAttributeType` anymore
There were big changes to the Compiler, am I right?
#### Edit:

I found the solution
this declaration seems to be outdated ([/examples/shader-generator/negatif.js](https://github.com/cedricpinson/osgjs/blob/master/examples/shader-generator/negatif.js))
`...
var NegatifAttribute = window.NegatifAttribute = function () {
        osg.StateAttribute.call( this );
        this._attributeEnable = false;
    };
    osg.createPrototypeStateAttribute( NegatifAttribute, osg.objectInherit( osg.StateAttribute.prototype, {
       // code
    } ), 'osg', 'Negatif' );
...`

Replace by using this here: ([/examples/shader-generator/CustomCompiler.js](https://github.com/cedricpinson/osgjs/blob/master/examples/shader-generator/CustomCompiler.js))
`...
NegatifAttribute.prototype = osg.objectLibraryClass( osg.objectInherit( osg.StateAttribute.prototype, {   
 // code
    } ), 'osg', 'Negatif' );
...`

And also in CustomCompiler remove those lines:
`
CustomCompiler.validAttributeType = osgShader.Compiler.validAttributeType.slice();
    CustomCompiler.validAttributeType.push( 'Negatif', 'Ramp' );
`

And add the validAttributeType to the ShaderGenerator instance: ([/examples/shader-generator/main.js](https://github.com/cedricpinson/osgjs/blob/master/examples/shader-generator/main.js))
`
var shaderGenerator = new osgShader.ShaderGenerator();
shaderGenerator.setShaderCompiler( CustomCompiler );
shaderGenerator._acceptAttributeTypes.add('Ramp');
shaderGenerator._acceptAttributeTypes.add('Negatif');
`

Took me quite a bit to figure this out...

**Comment by cedricpinson** [comment]
Ho sorry could you open a pull request with your changes ?

**Comment by cedricpinson** [comment]
fixed
