### ISSUE TITLE
Skewed textures on IE11

### ISSUE THREAD

**Issue by samylan** [cedricpinson/osgjs#670]
On IE11, textures get skewed if they are not on the first texture slot.
- if only one texture is set per StateSet : everything works fine
- if additional textures are set on the same StateSet, the new textures will get deformed. The first texture will still have a correct mapping thought.  

On Firefox 49 :  
![ff49](https://cloud.githubusercontent.com/assets/15139844/19076581/aae185be-8a49-11e6-9b80-5affb5cf7031.jpg)  
On Internet Explorer 11, you can see the first texture (small checkerboard) still being rendered correctly, but other textures that are above it are skewed :  
![ie11](https://cloud.githubusercontent.com/assets/15139844/19076585/acf342d4-8a49-11e6-8ef5-4788c74cfec7.jpg)

Test case :  
[IE11-multi-texture-bug.zip](https://github.com/cedricpinson/osgjs/files/508658/IE11-multi-texture-bug.zip)

**Comment by cedricpinson** [comment]
Not sure we can do something to fix it, Do you have the same issue with edge from MS ?

**Comment by samylan** [comment]
No, it works fine with Edge.

**Comment by cedricpinson** [comment]
Ok so probably it will be never fixed in ie11. I close it.
