### ISSUE TITLE
Coverity spotted dead code

### ISSUE THREAD

**Issue by jtorresfabra** [cedricpinson/osgjs#692]
Hi @stephomi, I guess you are the one that could fix this issue coverity spotted:

https://scan9.coverity.com/reports.htm#v25700/p12950/fileInstanceId=10394964&defectInstanceId=2039941&mergedDefectId=153346

https://github.com/cedricpinson/osgjs/blob/master/sources/osgShader/CompilerVertex.js#L307-L313

Besides the weird vairable assignement, last line (313) is not reachable. 

Thanks in advance.

**Comment by stephomi** [comment]
should be fixed by https://github.com/cedricpinson/osgjs/pull/697

**Comment by jtorresfabra** [comment]
Thanks man, I will trigger another coverity build when it gets merged :+1:
