### ISSUE TITLE
Remove metric outputs from ReaderParser.parseSceneGraph

### ISSUE THREAD

**Issue by andek714** [cedricpinson/osgjs#776]
ReaderParser.parseSceneGraph calls MACROUTILS.timeEnd which seems to use console.timeEnd and can't be suppressed by changing the notify level. Leads to tons of console outputs for a large number of PagedLods.

**Comment by cedricpinson** [comment]
@jtorresfabra maybe we should use the notify level to display it

**Comment by spotscale** [comment]
Created PR #798

**Comment by cedricpinson** [comment]
fixed #819
