### ISSUE TITLE
Erroneous light/material behavior

### ISSUE THREAD

**Issue by andek714** [cedricpinson/osgjs#783]
The point light setup here behaves erroneously when zooming in and out from the geometry:
http://projects.spotscale.com/osgjs_debug

The code is here:
http://projects.spotscale.com/osgjs_debug/js/main.js

Also, shifting to a directional light with setLightAsDirection, will cause a shift in appearance when zooming out from the geometry, suddenly slightly brighter.

**Comment by jtorresfabra** [comment]
https://github.com/cedricpinson/osgjs/pull/786 shoudl fix this
