### ISSUE TITLE
Recommended way to view same geometry in two cameras

### ISSUE THREAD

**Issue by spotscale** [cedricpinson/osgjs#797]
Adding the same geometry to two different viewers doesn't work in WebGL 1 which refuses to share arrays between contexts. So if there's another recommended way of doing this, e.g. a slave camera in the same viewer, there should be an example of how to accomplish that.

**Comment by jtorresfabra** [comment]
I would go for a fullscreen quad, render-to-texture each camera and assign texcoords to the quad depending on the desired layout.

To show/hide different combinations  of nodes depending on cameras one could use traversal masks.

Finally, hiding the logic into a CompositeViewer class coulbe be very useful to get a general purpose component.
