### ISSUE TITLE
Examples broken

### ISSUE THREAD

**Issue by vinou31** [cedricpinson/osgjs#813]
I attempt to understand how osgjs works goinr through examples but they don't work.

It could be the mismatch with the dependencies in the index.html :
`    <script type="text/javascript" src="../vendors/bluebird.js"></script>
    <script type="text/javascript" src="../vendors/hammer.js"></script>`
But when I look at the corresponding path I find :
`<script type="text/javascript" src="../vendors/bluebird-2.10.2.js"></script>
    <script type="text/javascript" src="../vendors/hammer-2.0.4.js"></script>`

So I made the change for one local index.html and it works.

**Comment by jtorresfabra** [comment]
Hi @vinou31, the examples should be accessed within a server. 
You will have a lot of errors if you try to access it directly as you did.

The easiest way is to follow the instructions in the Readme.md -> https://github.com/cedricpinson/osgjs#running-the-examples
