### ISSUE TITLE
How to convert osgjs format to obj or similar formats?

### ISSUE THREAD

**Issue by Ghost---Shadow** [cedricpinson/osgjs#892]
This [question on stackoverflow](https://stackoverflow.com/questions/11990094/converting-osg-format-to-3ds-or-obj) deals with how to convert .osg to .obj but I am using the WebGL version. The osgconv cant handle the .osgjs extention. I cannot find any tools to do so.

[Here is my post on stackoverflow. ](https://stackoverflow.com/questions/46864804/how-to-convert-osgjs-format-to-obj-or-similar-formats)

**Comment by cedricpinson** [comment]
There is some instructions here https://github.com/cedricpinson/osgjs/wiki/Convert-model-with-OSG that could help you

**Comment by Ghost---Shadow** [comment]
I want to do the reverse. Convert `osgjs` to `obj`. Typing `osgconv model.osgjs model.obj` doesnt work.

**Comment by hishamabdelrahman** [comment]
this wont work , only its one way of translation

**Comment by Ghost---Shadow** [comment]
Is there any way to salvage the models inside the `.osgjs` file?

**Comment by jtorresfabra** [comment]
Not that it already exists. But you can write your own writer though. It would be a nice addition.
