### ISSUE TITLE
osgjs029 can't work OpenSceneGraph 3.5.6

### ISSUE THREAD

**Issue by defineconst** [cedricpinson/osgjs#996]
osgjs file 's  version is 9 , OpenSceneGraph 3.5.6.

it is not display on osgjs029 ,notify.js:24 cant get file file.osgjs.gz status Typed Array Uint32Array.cant load file.osgjs.gz,Unhandled rejection Typed Array Int32Array.

how i can to resolve it???

many thanks for you~！

**Comment by saikiran321** [comment]
@defineconst  I'm facing similar issue. Did you find any solution ?

**Comment by cedricpinson** [comment]
I am sorry but I don’t work anymore on osgjs.
